//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsMedicinePurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsMedicinePurchase()
        {
            this.DetailMedicinePurchases = new HashSet<DetailMedicinePurchase>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailMedicinePurchase> DetailMedicinePurchases { get; set; }
    }
}
